/*创建数据库*/
CREATE DATABASE dati;
USE dati;
/*创建题库表 主键ID */
DROP TABLE IF EXISTS tiku;
CREATE TABLE tiku (
  tkid INT(11) NOT NULL AUTO_INCREMENT,
  tkname VARCHAR(60) DEFAULT NULL,
  tkscore VARCHAR(10) DEFAULT NULL,
  kcnames VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tkid)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
/*创建题目表 主键为ID type类型有 单选题 多选题 判断题 简答题*/
DROP TABLE IF EXISTS timu;
CREATE TABLE  timu (
  tmid INT(11) NOT NULL AUTO_INCREMENT,
  tmname VARCHAR(100) DEFAULT NULL,
  tmtype VARCHAR(6)  DEFAULT NULL,
  optionA VARCHAR(50) DEFAULT NULL,
  optionB VARCHAR(50) DEFAULT NULL,
  optionC VARCHAR(50) DEFAULT NULL,
  optionD VARCHAR(50) DEFAULT NULL,
  answer VARCHAR(500) DEFAULT NULL,
  tmscore INT(10) DEFAULT NULL,
  tknames VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tmid)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
/*创建关系表tiku_timu 主键为tkid+tmid */
DROP TABLE IF EXISTS tiku_timu;
CREATE TABLE tiku_timu(
   tkid INT(11),
   tmid INT(11),
   PRIMARY KEY (tkid,tmid),
   FOREIGN KEY (tkid) REFERENCES tiku(tkid),
   FOREIGN KEY (tmid) REFERENCES timu(tmid)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

/*创建考场表 主键为ID*/
DROP TABLE IF EXISTS kc;
CREATE TABLE kc(
  kcid INT(11) NOT NULL AUTO_INCREMENT,
  kcname VARCHAR(60) DEFAULT NULL,
  starttime VARCHAR(60) DEFAULT NULL,
  endtime VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY (kcid)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
/*创建kc_tiku 主键为kcid+tkid*/
DROP TABLE IF EXISTS kc_tiku;
CREATE TABLE kc_tiku(
   kcid INT(11),
   tkid INT(11),
   PRIMARY KEY (kcid,tkid),
   FOREIGN KEY (tkid) REFERENCES tiku(tkid),
   FOREIGN KEY (kcid) REFERENCES kc(kcid)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
/*创建面试官表 主键为id*/
DROP TABLE IF EXISTS msg;
CREATE TABLE msg(
  msgid INT(11) NOT NULL AUTO_INCREMENT,
  msgaccount VARCHAR(60) NOT NULL,
  msgpwd VARCHAR(60) DEFAULT NULL, 
  msgname VARCHAR(60) DEFAULT NULL,
  msgphone VARCHAR(60) DEFAULT NULL,
  kcid INT(11) DEFAULT NULL,
  PRIMARY KEY (msgid),
  FOREIGN KEY (kcid) REFERENCES kc(kcid)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

/*创建用户表 主键为id*/
DROP TABLE IF EXISTS users;
CREATE TABLE users(
  usersid INT(11) NOT NULL AUTO_INCREMENT,
  usersname VARCHAR(60) DEFAULT NULL,
  xingbie VARCHAR(2) DEFAULT NULL,
  dianhua VARCHAR(20) DEFAULT NULL,
  xuexiao VARCHAR(20) DEFAULT NULL,
  zhuanye VARCHAR(20) DEFAULT NULL,
  xueli VARCHAR(20) DEFAULT NULL,
  wxname VARCHAR(20) DEFAULT NULL,
  openid VARCHAR(50) DEFAULT NULL,
  kcid INT(11) DEFAULT NULL,
  kgtscore INT(10) DEFAULT NULL,
  zgtscore INT(10) DEFAULT NULL,
  score INT (10) DEFAULT NULL,
  PRIMARY KEY (usersid),
  FOREIGN KEY (kcid) REFERENCES kc(kcid)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
/*用于存储主观题答案*/
DROP TABLE IF EXISTS users_zgt;
CREATE TABLE users_zgt(
  tmid INT(11) DEFAULT NULL,
  openid VARCHAR(50) DEFAULT NULL,
  usersname VARCHAR(60) DEFAULT NULL,
  tmname VARCHAR(100) DEFAULT NULL,
  tmscore VARCHAR(10) DEFAULT NULL,
  zgtanswer VARCHAR(1000) DEFAULT NULL,
  zgtscore INT(10) DEFAULT NULL,
  ispingyue VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (tmid,openid),
  FOREIGN KEY (tmid) REFERENCES timu(tmid)
 )ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
 
/*创建管理员表 主键为id*/
DROP TABLE IF EXISTS admin;
CREATE TABLE admin(
  adid INT(11) NOT NULL AUTO_INCREMENT,
  adname VARCHAR(60) DEFAULT NULL,
  adpwd VARCHAR(60) DEFAULT NULL, 
  PRIMARY KEY (adid)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


/*创建allResult表 储存所有用户的答案对错  主键为kcid+tkid */
DROP TABLE IF EXISTS allresult;
CREATE TABLE allresult(
  openid VARCHAR(50) DEFAULT NULL,
  kcid INT(11) DEFAULT NULL,
  tkid INT(11) DEFAULT NULL,
  results VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (openid),
  FOREIGN KEY (tkid) REFERENCES tiku(tkid),
  FOREIGN KEY (kcid) REFERENCES kc(kcid)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

